---
title: "malaria_exploratory"
author: "Krti Tallam"
date: "11/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages

library('lme4')
library('plotly')
library('QuantPsyc')
library('sem')
```

```{r}
# Read in data

predictors <- read.csv('/enterPathHere/malaria_predictors_all.csv')
avg_loss <- read.csv('/enterPathHere/avg-losses_2001-2019.csv')
log_loss <- read.csv('/enterPathHere/log-of-loss.csv')

View(predictors)
View(avg_loss)
View(log_loss)
```

```{r}
# Visualization 

par(mfrow=c(2,4))
p1 <- plot(predictors$palu.pc.2nn_0.08 ~ predictors$malaria.all.lag, predictors)
abline(lm(predictors$palu.pc.2nn_0.08 ~ predictors$malaria.all.lag), col = "red")

p2 <- plot(predictors$palu.pc.2nn_0.08 ~ predictors$forest.cover, predictors)
abline(lm(predictors$palu.pc.2nn_0.08 ~ predictors$forest.cover), col = "red")

p3 <- plot(palu.pc.2nn_0.08 ~ predictors$monthly.max.t.lag, predictors)
abline(lm(predictors$palu.pc.2nn_0.08 ~ predictors$monthly.max.t.lag), col = "red")

p4 <- plot(palu.pc.2nn_0.08 ~ predictors$monthly.min.t.lag, predictors)
abline(lm(predictors$palu.pc.2nn_0.08 ~ predictors$monthly.min.t.lag), col = "red")

p5 <- plot(palu.pc.2nn_0.08 ~ predictors$monthly.p.lag, predictors)
abline(lm(predictors$palu.pc.2nn_0.08 ~ predictors$monthly.p.lag), col = "red")

p6 <- plot(palu.pc.2nn_0.08 ~ predictors$altitude, predictors)
abline(lm(predictors$palu.pc.2nn_0.08 ~ predictors$altitude), col = "red")

p7 <- plot(palu.pc.2nn_0.08 ~ predictors$loss.14, predictors)
abline(lm(predictors$palu.pc.2nn_0.08 ~ predictors$loss.14), col = "red")

p8 <- boxplot(predictors$palu.pc.2nn_0.08 ~ predictors$med.veg, predictors)
abline(lm(predictors$palu.pc.2nn_0.08 ~ predictors$malaria.all.lag), col = "red")


par(mfrow=c(1,1))
```

```{r}
# Adult malaria
time.corr <- lm(predictors$palu.pc.2nn_0.08 ~ predictors$malaria.all.lag)
summary(time.corr)
plot(predictors$palu.pc.2nn_0.08,predictors$malaria.all.lag)
abline(lm(predictors$palu.pc.2nn_0.08 ~ predictors$malaria.all.lag), col = "red")

pop.corr <- lm(palu.pc.2nn_0.08 ~ predictors$malaria.all.lag + Population, predictors)
summary(pop.corr)
abline(lm(predictors$palu.pc.2nn_0.08 ~ predictors$malaria.all.lag), col = "red")

weather.corr <- lm(predictors$palu.pc.2nn_0.08 ~ predictors$monthly.p.lag + predictors$monthly.max.t.lag + predictors$monthly.min.t.lag + predictors$altitude, predictors)
summary(weather.corr)
abline(lm(predictors$palu.pc.2nn_0.08 ~ predictors$monthly.p.lag + predictors$monthly.max.t.lag + predictors$monthly.min.t.lag + predictors$altitude), col = "red")

land.corr <-  lm(palu.pc.2nn_0.08 ~ month + monthly.p.lag + monthly.max.t.lag + monthly.min.t.lag + altitude + forest.cover + loss.14 + loss.10 + med.veg, predictors)
summary(land.corr)
abline(lm(predictors$palu.pc.2nn_0.08 ~ predictors$monthly.p.lag + predictors$monthly.max.t.lag + predictors$monthly.min.t.lag + predictors$altitude + predictors$forest.cover + predictors$loss.14 + predictors$loss.10 + predictors$med.veg, predictors), col = "red")

tot.corr <- lm(palu.pc.2nn_0.08 ~ malaria.all.lag + monthly.p.lag + monthly.max.t.lag + monthly.min.t.lag + altitude + forest.cover + loss.14 + loss.10 + med.veg, predictors)
summary(tot.corr)
abline(lm(predictors$palu.pc.2nn_0.08 ~ predictors$malaria.all.lag), col = "red")
```

```{r}
# Children malaria

weather.corr <- lm(palu.und5.pc.3nn_0.19 ~ monthly.p.lag + monthly.max.t.lag + monthly.min.t.lag + altitude, predictors)
summary(weather.corr)
plot(predictors$palu.und5.pc.3nn_0.19, monthly.p.lag + monthly.max.t.lag + monthly.min.t.lag + altitude, predictors)
abline(lm(predictors$palu.und5.pc.3nn_0.19 ~ monthly.p.lag + monthly.max.t.lag + monthly.min.t.lag + altitude, predictors), col = "red")
```

```{r}
# Building our datasets 

malaria <- read.csv('dat_izzy_May15.csv')

alt <- read.csv('altitude.bf.csv') # Read altitude
bednets <- read.csv('bednets.bs.bf.csv') # Read bed net use

malaria$altitude <- 0
malaria$nets.high <- 0
malaria$nets.low <- 0

for (i in 0:194){
  
  malaria$altitude[malaria$ID == i] <- alt$alt_bf[i+1]
  malaria$nets.high[malaria$ID == i] <- bednets$highseason[i+1]
  malaria$nets.low[malaria$ID == i] <- bednets$lowseason[i+1]
  
}
```

```{r}
# Statistical Testing

print(chisq.test(predictors$forest.cover)) # it won't test on malaria prevalence because of all the NA values.

Xsq <- chisq.test(predictors$forest.cover)
Xsq$observed   # observed counts (same as M)
Xsq$expected   # expected counts under the null
Xsq$residuals  # Pearson residuals
Xsq$stdres     # standardized residuals
```


```{r}
# Regression

pairs(avg_loss)

loss_reg <- lm(avg_loss$AVERAGES ~ avg_loss$CUMULATIVE, data = avg_loss)
View(loss_reg)

Anova(loss_reg)

summary(loss_reg)$r.squared

full_mediation_loss_reg <- lm(avg_loss$AVERAGES ~ avg_loss$CUMULATIVE, data = avg_loss)
summary(full_mediation_loss_reg)$r.squared
lm.beta(full_mediation_loss_reg)   #quantpsyc
```


```{r}
# SEM Modeling

# Needed packages to perform the analysis: KT already did, do NOT need to do again!

load <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg))
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
} 
packages <- c("lavaan","semPlot","semTools","nonnest2","htmlTable")
load(packages)


# Loss Model 

log_loss <- read.csv('/enterPathHere/log-of-loss.csv')

loss.model <- '/enterPathHere/log-of-loss.csv'
  
#  'loss1 =~ log_loss$log_loss.01 + log_loss$log_loss.02 + log_loss$log_loss.03     
           #   loss2 =~ log_loss$log_loss.04 + log_loss$log_loss.05 + log_loss$log_loss.06 
            #  loss3 =~ log_loss$log_loss.07 + log_loss$log_loss.08 + log_loss$log_loss.09'


# Fit the model

fit <- cfa(loss.model, data = log_loss)

summary(fit, fit.measures = FALSE)
parameterEstimates(fit, ci = TRUE, level = 0.95)
fitMeasures(fit, c("chisq", "rmsea", "srmr", "gfi", "ecvi"))
reliability(fit)

# Export lavaan to output tables (if we want)
htmlTable(txtRound(parameterEstimates(fit, ci = TRUE, level = 0.95), digits=3, excl.cols=1), align="l|r|r|r|r|r|r|r|r|r")
htmlTable(txtRound(reliability(fit),3), align="l|r|r|r|r")

# Creating an SEM diagram
# svg("sem_r/cfa_example_2.svg")
semPaths(fit, style="lisrel", 
        whatLabels = "std", edge.label.cex = .6, node.label.cex = .6, 
        label.prop=0.9, edge.label.color = "black", rotation = 4, 
        equalizeManifests = FALSE, optimizeLatRes = TRUE, node.width = 1.5, 
        edge.width = 0.5, shapeMan = "rectangle", shapeLat = "ellipse", 
        shapeInt = "triangle", sizeMan = 4, sizeInt = 2, sizeLat = 4, 
        curve=2, unCol = "#070b8c")
dev.off()
```


```{r}
# Breier Curve

# B = Brière (qT[T – Tmin][ Tmax - T]1/2)

# q (CIs) = 1.06·10-4(0.88–1.26·10-4)
# Tmin (CIs) = 14.1(13.1–15.2)
# Tmax (CIs) = 34.2(33.5–34.8)
# Topt (CIs) = 29.2(28.7–29.7) ... 

# ... at 95% CI.

# Optimal ranges for Anopheles: 17 to 19°C and from 27 to 33°C

Bl1 = ((1.06(10^-4(0.88–1.26·10^-4))))[17 – (14.1(13.1–15.2)][(34.2(33.5–34.8)) - 17]1/2)
Bh1 = ((1.06(10^-4(0.88–1.26·10^-4))))[19 – (14.1(13.1–15.2)][(34.2(33.5–34.8)) - 19]1/2)
Bl2 = ((1.06(10^-4(0.88–1.26·10^-4))))[27 – (14.1(13.1–15.2)][(34.2(33.5–34.8)) - 27]1/2)
Bh2 = ((1.06(10^-4(0.88–1.26·10^-4))))[33 – (14.1(13.1–15.2)][(34.2(33.5–34.8)) - 33]1/2)
```


```{r}
#  Fit R_0
```


```{r}
# Check out the MVSE package: https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13205

```









